- hosts: localhost
  become: true
  become_user: root
  pre_tasks:

  - name: Update apt cache
    tags: always
    apt:
      update_cache: yes

- hosts: localhost
  become: true
  become_user: root
  roles:
    - 2hosts
